# Generated by Django 4.1 on 2022-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"error": "Bunday email mavjud."},
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
