# Generated by Django 4.1 on 2022-08-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="chat/")),
                ("is_group", models.BooleanField(default=False)),
                (
                    "is_archived",
                    models.ManyToManyField(
                        related_name="user_archived", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="chat", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "pinned",
                    models.ManyToManyField(
                        related_name="user_pinned", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "unmuted",
                    models.ManyToManyField(
                        related_name="user_unmuted", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "read",
                    models.ManyToManyField(
                        related_name="user_read", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
